import streamlit as st
import yfinance as yf
import pandas as pd
import numpy as np

st.set_page_config(page_title="NSE Comprehensive BTST Screener", page_icon="⚡", layout="wide")

st.title("⚡ Comprehensive NSE F&O & Cash BTST Multi-Screener")
st.markdown("""
This production scanner includes an expansive list of **140+ active F&O derivatives stocks** mapping custom lot sizes and strike mechanics, alongside the top cash market list.
""")

# Universe 1: Standard Liquid Nifty Stocks (Cash Segment)
NIFTY_200_CASH = [
    "RELIANCE.NS", "TCS.NS", "INFY.NS", "HDFCBANK.NS", "ICICIBANK.NS", "BHARTIARTL.NS", "SBIN.NS", "ITC.NS", "LT.NS", "M&M.NS",
    "SUNPHARMA.NS", "TATAMOTORS.NS", "AXISBANK.NS", "ASIANPAINT.NS", "HCLTECH.NS", "NTPC.NS", "ONGC.NS", "POWERGRID.NS", "COALINDIA.NS", "TITAN.NS",
    "BAJAJ-AUTO.NS", "BAJFINANCE.NS", "BAJAJFINSV.NS", "ULTRACEMCO.NS", "NESTLEIND.NS", "JIOFIN.NS", "ADANIENT.NS", "ADANIPORTS.NS", "ADANIGREEN.NS", "ADANIPOWER.NS",
    "TATASTEEL.NS", "HINDALCO.NS", "JSWSTEEL.NS", "GRASIM.NS", "LTIM.NS", "TECHM.NS", "WIPRO.NS", "HINDUNILVR.NS", "BRITANNIA.NS", "CIPLA.NS",
    "DRREDDY.NS", "DIVISLAB.NS", "APOLLOHOSP.NS", "EICHERMOT.NS", "HEROMOTOCO.NS", "BPCL.NS", "IOC.NS", "BEL.NS", "HAL.NS", "DLF.NS",
    "VBL.NS", "ZOMATO.NS", "TRENT.NS", "PIDILITIND.NS", "SIEMENS.NS", "ABB.NS", "INDIGO.NS", "TATACONSUM.NS", "SHRIRAMFIN.NS", "CHOLAFIN.NS",
    "PFC.NS", "RECL.NS", "GAIL.NS", "SAIL.NS", "NMDC.NS", "GMRINFRA.NS", "IDEA.NS", "PNB.NS", "BANKBARODA.NS", "CANBK.NS"
]

# Expansive Universe 2: Over 140+ active F&O stocks with mapped Lot Sizes and Strike Increments
FANDO_OPTIONS = {
    "AARTIIND": {"symbol": "AARTIIND.NS", "lot_size": 1000, "strike_step": 10},
    "ABB": {"symbol": "ABB.NS", "lot_size": 125, "strike_step": 100},
    "ABBOTINDIA": {"symbol": "ABBOTINDIA.NS", "lot_size": 20, "strike_step": 200},
    "ABCAPITAL": {"symbol": "ABCAPITAL.NS", "lot_size": 2700, "strike_step": 2.5},
    "ABFRL": {"symbol": "ABFRL.NS", "lot_size": 1300, "strike_step": 5},
    "ACC": {"symbol": "ACC.NS", "lot_size": 300, "strike_step": 20},
    "ADANIENT": {"symbol": "ADANIENT.NS", "lot_size": 300, "strike_step": 50},
    "ADANIPORTS": {"symbol": "ADANIPORTS.NS", "lot_size": 400, "strike_step": 20},
    "ALKEM": {"symbol": "ALKEM.NS", "lot_size": 100, "strike_step": 100},
    "AMBUJACEM": {"symbol": "AMBUJACEM.NS", "lot_size": 800, "strike_step": 10},
    "APOLLOHOSP": {"symbol": "APOLLOHOSP.NS", "lot_size": 125, "strike_step": 100},
    "APOLLOTYRE": {"symbol": "APOLLOTYRE.NS", "lot_size": 1700, "strike_step": 5},
    "ASHOKLEY": {"symbol": "ASHOKLEY.NS", "lot_size": 2500, "strike_step": 2.5},
    "ASIANPAINT": {"symbol": "ASIANPAINT.NS", "lot_size": 200, "strike_step": 20},
    "ASTRAL": {"symbol": "ASTRAL.NS", "lot_size": 361, "strike_step": 20},
    "ATUL": {"symbol": "ATUL.NS", "lot_size": 75, "strike_step": 100},
    "AUBANK": {"symbol": "AUBANK.NS", "lot_size": 1000, "strike_step": 10},
    "AUROPHARMA": {"symbol": "AUROPHARMA.NS", "lot_size": 550, "strike_step": 10},
    "AXISBANK": {"symbol": "AXISBANK.NS", "lot_size": 625, "strike_step": 10},
    "BAJAJ-AUTO": {"symbol": "BAJAJ-AUTO.NS", "lot_size": 125, "strike_step": 100},
    "BAJAJFINSV": {"symbol": "BAJAJFINSV.NS", "lot_size": 500, "strike_step": 20},
    "BAJFINANCE": {"symbol": "BAJFINANCE.NS", "lot_size": 125, "strike_step": 100},
    "BALRAMCHIN": {"symbol": "BALRAMCHIN.NS", "lot_size": 1600, "strike_step": 5},
    "BANDHANBNK": {"symbol": "BANDHANBNK.NS", "lot_size": 2500, "strike_step": 2.5},
    "BANKBARODA": {"symbol": "BANKBARODA.NS", "lot_size": 2425, "strike_step": 2.5},
    "BATAINDIA": {"symbol": "BATAINDIA.NS", "lot_size": 375, "strike_step": 20},
    "BEL": {"symbol": "BEL.NS", "lot_size": 2850, "strike_step": 2.5},
    "BERGEPAINT": {"symbol": "BERGEPAINT.NS", "lot_size": 1100, "strike_step": 5},
    "BHARATFORG": {"symbol": "BHARATFORG.NS", "lot_size": 500, "strike_step": 20},
    "BHARTIARTL": {"symbol": "BHARTIARTL.NS", "lot_size": 950, "strike_step": 10},
    "BHEL": {"symbol": "BHEL.NS", "lot_size": 2625, "strike_step": 2.5},
    "BIOCON": {"symbol": "BIOCON.NS", "lot_size": 1600, "strike_step": 5},
    "BOSCHLTD": {"symbol": "BOSCHLTD.NS", "lot_size": 20, "strike_step": 200},
    "BPCL": {"symbol": "BPCL.NS", "lot_size": 1800, "strike_step": 5},
    "BRITANNIA": {"symbol": "BRITANNIA.NS", "lot_size": 200, "strike_step": 50},
    "BSOFT": {"symbol": "BSOFT.NS", "lot_size": 1000, "strike_step": 10},
    "CANFINHOME": {"symbol": "CANFINHOME.NS", "lot_size": 975, "strike_step": 10},
    "CANBK": {"symbol": "CANBK.NS", "lot_size": 2250, "strike_step": 1},
    "CHAMBLFERT": {"symbol": "CHAMBLFERT.NS", "lot_size": 1900, "strike_step": 5},
    "CHOLAFIN": {"symbol": "CHOLAFIN.NS", "lot_size": 625, "strike_step": 20},
    "CIPLA": {"symbol": "CIPLA.NS", "lot_size": 650, "strike_step": 10},
    "COALINDIA": {"symbol": "COALINDIA.NS", "lot_size": 2100, "strike_step": 5},
    "COFORGE": {"symbol": "COFORGE.NS", "lot_size": 150, "strike_step": 100},
    "COLPAL": {"symbol": "COLPAL.NS", "lot_size": 350, "strike_step": 20},
    "CONCOR": {"symbol": "CONCOR.NS", "lot_size": 1000, "strike_step": 10},
    "COROMANDEL": {"symbol": "COROMANDEL.NS", "lot_size": 700, "strike_step": 20},
    "CROMPTON": {"symbol": "CROMPTON.NS", "lot_size": 1800, "strike_step": 5},
    "CUMMINSIND": {"symbol": "CUMMINSIND.NS", "lot_size": 300, "strike_step": 20},
    "DABUR": {"symbol": "DABUR.NS", "lot_size": 1250, "strike_step": 5},
    "DALBHARAT": {"symbol": "DALBHARAT.NS", "lot_size": 250, "strike_step": 20},
    "DEEPAKNTR": {"symbol": "DEEPAKNTR.NS", "lot_size": 300, "strike_step": 20},
    "DELTACORP": {"symbol": "DELTACORP.NS", "lot_size": 3000, "strike_step": 2.5},
    "DIVISLAB": {"symbol": "DIVISLAB.NS", "lot_size": 200, "strike_step": 50},
    "DIXON": {"symbol": "DIXON.NS", "lot_size": 100, "strike_step": 100},
    "DLF": {"symbol": "DLF.NS", "lot_size": 1650, "strike_step": 10},
    "DRREDDY": {"symbol": "DRREDDY.NS", "lot_size": 125, "strike_step": 50},
    "EICHERMOT": {"symbol": "EICHERMOT.NS", "lot_size": 175, "strike_step": 50},
    "ESCORTS": {"symbol": "ESCORTS.NS", "lot_size": 275, "strike_step": 50},
    "EXIDEIND": {"symbol": "EXIDEIND.NS", "lot_size": 1800, "strike_step": 5},
    "FEDERALBNK": {"symbol": "FEDERALBNK.NS", "lot_size": 5000, "strike_step": 2.5},
    "GAIL": {"symbol": "GAIL.NS", "lot_size": 4550, "strike_step": 2.5},
    "GLENMARK": {"symbol": "GLENMARK.NS", "lot_size": 725, "strike_step": 10},
    "GMRINFRA": {"symbol": "GMRINFRA.NS", "lot_size": 11250, "strike_step": 1},
    "GNFC": {"symbol": "GNFC.NS", "lot_size": 1300, "strike_step": 10},
    "GODREJCP": {"symbol": "GODREJCP.NS", "lot_size": 500, "strike_step": 10},
    "GODREJPROP": {"symbol": "GODREJPROP.NS", "lot_size": 325, "strike_step": 20},
    "GRANULES": {"symbol": "GRANULES.NS", "lot_size": 2000, "strike_step": 5},
    "GRASIM": {"symbol": "GRASIM.NS", "lot_size": 250, "strike_step": 20},
    "GUJGASLTD": {"symbol": "GUJGASLTD.NS", "lot_size": 1250, "strike_step": 10},
    "HAL": {"symbol": "HAL.NS", "lot_size": 300, "strike_step": 20},
    "HAVELLS": {"symbol": "HAVELLS.NS", "lot_size": 500, "strike_step": 20},
    "HCLTECH": {"symbol": "HCLTECH.NS", "lot_size": 700, "strike_step": 10},
    "HDFCBANK": {"symbol": "HDFCBANK.NS", "lot_size": 550, "strike_step": 10},
    "HDFCLIFE": {"symbol": "HDFCLIFE.NS", "lot_size": 1100, "strike_step": 5},
    "HEROMOTOCO": {"symbol": "HEROMOTOCO.NS", "lot_size": 150, "strike_step": 50},
    "HINDALCO": {"symbol": "HINDALCO.NS", "lot_size": 1400, "strike_step": 5},
    "HINDCOPPER": {"symbol": "HINDCOPPER.NS", "lot_size": 2800, "strike_step": 5},
    "HINDPETRO": {"symbol": "HINDPETRO.NS", "lot_size": 1350, "strike_step": 5},
    "HINDUNILVR": {"symbol": "HINDUNILVR.NS", "lot_size": 300, "strike_step": 20},
    "ICICIBANK": {"symbol": "ICICIBANK.NS", "lot_size": 700, "strike_step": 5},
    "ICICIGI": {"symbol": "ICICIGI.NS", "lot_size": 500, "strike_step": 20},
    "ICICIPRULI": {"symbol": "ICICIPRULI.NS", "lot_size": 1500, "strike_step": 10},
    "IDEA": {"symbol": "IDEA.NS", "lot_size": 40000, "strike_step": 0.5},
    "IDFCFIRSTB": {"symbol": "IDFCFIRSTB.NS", "lot_size": 7500, "strike_step": 1},
    "IEX": {"symbol": "IEX.NS", "lot_size": 3750, "strike_step": 2.5},
    "IGL": {"symbol": "IGL.NS", "lot_size": 1375, "strike_step": 5},
    "INDHOTEL": {"symbol": "INDHOTEL.NS", "lot_size": 1000, "strike_step": 5},
    "INDIACEM": {"symbol": "INDIACEM.NS", "lot_size": 2900, "strike_step": 2.5},
    "INDIAMART": {"symbol": "INDIAMART.NS", "lot_size": 150, "strike_step": 50},
    "INDIGO": {"symbol": "INDIGO.NS", "lot_size": 150, "strike_step": 50},
    "INDUSINDBK": {"symbol": "INDUSINDBK.NS", "lot_size": 500, "strike_step": 10},
    "INDUSTOWER": {"symbol": "INDUSTOWER.NS", "lot_size": 1700, "strike_step": 5},
    "INFY": {"symbol": "INFY.NS", "lot_size": 400, "strike_step": 10},
    "IOC": {"symbol": "IOC.NS", "lot_size": 3375, "strike_step": 2.5},
    "IPCALAB": {"symbol": "IPCALAB.NS", "lot_size": 650, "strike_step": 10},
    "IRCTC": {"symbol": "IRCTC.NS", "lot_size": 875, "strike_step": 10},
    "ITC": {"symbol": "ITC.NS", "lot_size": 1600, "strike_step": 5},
    "JINDALSTEL": {"symbol": "JINDALSTEL.NS", "lot_size": 1250, "strike_step": 10},
    "JKCEMENT": {"symbol": "JKCEMENT.NS", "lot_size": 250, "strike_step": 50},
    "JSWSTEEL": {"symbol": "JSWSTEEL.NS", "lot_size": 675, "strike_step": 10},
    "JUBLFOOD": {"symbol": "JUBLFOOD.NS", "lot_size": 1250, "strike_step": 5},
    "KOTAKBANK": {"symbol": "KOTAKBANK.NS", "lot_size": 400, "strike_step": 20},
    "L&TFH": {"symbol": "L&TFH.NS", "lot_size": 4444, "strike_step": 2.5},
    "LALPATHLAB": {"symbol": "LALPATHLAB.NS", "lot_size": 300, "strike_step": 50},
    "LICHSGFIN": {"symbol": "LICHSGFIN.NS", "lot_size": 1000, "strike_step": 10},
    "LT": {"symbol": "LT.NS", "lot_size": 300, "strike_step": 20},
